config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :book_tables
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/authorbook.rb
class Authorbook < ApplicationRecord
end

app/models/book_table.rb
class BookTable < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:author_name, :Birth_year)
    end
end

app/controllers/book_tables_controller.rb
class BookTablesController < ApplicationController
  before_action :set_book_table, only: %i[ show edit update destroy ]

  # GET /book_tables or /book_tables.json
  def index
    @book_tables = BookTable.all
  end

  # GET /book_tables/1 or /book_tables/1.json
  def show
  end

  # GET /book_tables/new
  def new
    @book_table = BookTable.new
  end

  # GET /book_tables/1/edit
  def edit
  end

  # POST /book_tables or /book_tables.json
  def create
    @book_table = BookTable.new(book_table_params)

    respond_to do |format|
      if @book_table.save
        format.html { redirect_to @book_table, notice: "Book table was successfully created." }
        format.json { render :show, status: :created, location: @book_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_tables/1 or /book_tables/1.json
  def update
    respond_to do |format|
      if @book_table.update(book_table_params)
        format.html { redirect_to @book_table, notice: "Book table was successfully updated." }
        format.json { render :show, status: :ok, location: @book_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_tables/1 or /book_tables/1.json
  def destroy
    @book_table.destroy
    respond_to do |format|
      format.html { redirect_to book_tables_url, notice: "Book table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_table
      @book_table = BookTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_table_params
      params.require(:book_table).permit(:Book_id, :Book_title, :Published_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_tables_helper.rb
module BookTablesHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author_name %>
    <%= form.text_field :author_name %>
  </div>

  <div class="field">
    <%= form.label :Birth_year %>
    <%= form.number_field :Birth_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Author name</th>
      <th>Birth year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.author_name %></td>
        <td><%= author.Birth_year %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author name:</strong>
  <%= @author.author_name %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @author.Birth_year %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/book_tables/_form.html.erb
<%= form_with(model: book_table) do |form| %>
  <% if book_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_table.errors.count, "error") %> prohibited this book_table from being saved:</h2>

      <ul>
        <% book_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Book_id %>
    <%= form.text_field :Book_id %>
  </div>

  <div class="field">
    <%= form.label :Book_title %>
    <%= form.text_field :Book_title %>
  </div>

  <div class="field">
    <%= form.label :Published_year %>
    <%= form.number_field :Published_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_tables/edit.html.erb
<h1>Editing Book Table</h1>

<%= render 'form', book_table: @book_table %>

<%= link_to 'Show', @book_table %> |
<%= link_to 'Back', book_tables_path %>

app/views/book_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Tables</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Book title</th>
      <th>Published year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_tables.each do |book_table| %>
      <tr>
        <td><%= book_table.Book_id %></td>
        <td><%= book_table.Book_title %></td>
        <td><%= book_table.Published_year %></td>
        <td><%= link_to 'Show', book_table %></td>
        <td><%= link_to 'Edit', edit_book_table_path(book_table) %></td>
        <td><%= link_to 'Destroy', book_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Table', new_book_table_path %>

app/views/book_tables/new.html.erb
<h1>New Book Table</h1>

<%= render 'form', book_table: @book_table %>

<%= link_to 'Back', book_tables_path %>

app/views/book_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book_table.Book_id %>
</p>

<p>
  <strong>Book title:</strong>
  <%= @book_table.Book_title %>
</p>

<p>
  <strong>Published year:</strong>
  <%= @book_table.Published_year %>
</p>

<%= link_to 'Edit', edit_book_table_path(@book_table) %> |
<%= link_to 'Back', book_tables_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foreignkeyook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>